#Autogenerated by ReportLab guiedit do not edit
from reportlab.graphics.charts.piecharts import Pie
from reportlab.lib.colors import darkcyan, blue, cyan
from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin
from reportlab.lib.styles import black, white
from reportlab.graphics.charts.textlabels import Label

class Drawing_000(_DrawingEditorMixin,Drawing):
    def __init__(self,width=400,height=200,*args,**kw):
        Drawing.__init__(self,width,height,*args,**kw)
        self._add(self,Pie(),name=None,validate=None,desc=None)

        # Set the size and location of the chart
        self.contents[0].width             = 120
        self.contents[0].height            = 120
        self.contents[0].y                 = 40
        self.contents[0].x                 = 130

        # Fill in the chart with sample data and labels
        self.contents[0].data              = [1, 2, 1.8, 4, 1, 8]
        self.contents[0].labels            = ['test3','Label2','Label3','Label4','Label5','Label6','Label7']

        # Make the slices pop out and add a border to the slices
        self.contents[0].slices.popout                    = 5
        self.contents[0].slices.strokeWidth               = 1


        # Set the font size and position the label
        self.contents[0].slices.fontSize                  = 14
        self.contents[0].slices.labelRadius               = 1.25

        # Turn off simple labels so we can use customized labels
        self.contents[0].simpleLabels                     = 0
        # Define a simple pointer for all labels
        self.contents[0].slices.label_simple_pointer      = 1

        # Define a first label with a black border,
        # white text and dark cyan background
        self.contents[0].slices[0].label_boxStrokeColor   = black
        self.contents[0].slices[0].fontColor              = white
        self.contents[0].slices[0].label_boxFillColor     = darkcyan
        # Change the anchor point of the label box
        self.contents[0].slices[0].label_boxAnchor        = 's'

        # Turn off pointer for the third label, change the text color
        self.contents[0].slices[2].label_simple_pointer   = 0
        self.contents[0].slices[2].fontColor              = blue
        # and position it closer to the chart
        self.contents[0].slices[2].labelRadius            = 1.05

        # Turn off pointer for the fourth label
        # and position it within the chart
        self.contents[0].slices[3].label_simple_pointer  = 0
        self.contents[0].slices[3].labelRadius           = 0.25

        # Define a fifth label with a black border, text padding
        # and position it closer to the chart
        self.contents[0].slices[4].label_boxStrokeColor  = black
        self.contents[0].slices[4].label_height          = 22
        self.contents[0].slices[4].label_topPadding      = 2
        self.contents[0].slices[4].label_leftPadding     = 6
        self.contents[0].slices[4].label_rightPadding    = 6
        self.contents[0].slices[4].labelRadius           = 1.15

        # Change font size for the sixth label
        self.contents[0].slices[5].fontSize              = 20

if __name__=="__main__": #NORUNTESTS
    Drawing_000().save(formats=['png'],outDir='.',fnRoot=None)
